### ISSUE TITLE
[FEATURE] Ingress support

### ISSUE THREAD

**Issue by sorvihead** [sorvihead/vscode-python-template#1]
### **Summary**
Add comprehensive Ingress support to enable external access to the application with clean URLs and SSL/TLS termination capabilities.

### **Problem Statement**
Currently, the application can only be accessed through:
- `kubectl port-forward` (manual, not persistent)
- NodePort service (requires specific ports, not production-ready)
- Direct service access within cluster only

This limits development workflow and prevents proper production deployment patterns.

#### **1. Helm Chart Enhancements**
```yaml
# values.yaml additions
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: project-template.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
```

#### **2. Template Implementation**
- Create `helm/templates/ingress.yaml` with:
  - Kubernetes version compatibility (1.14+)
  - Conditional rendering based on `ingress.enabled`
  - Support for multiple hosts and paths
  - TLS/SSL certificate integration
  - Annotation-based ingress controller configuration

#### **3. Development Environment Integration**
- Update Minikube configuration with ingress enabled by default
- Add `/etc/hosts` setup instructions
- Include ingress controller setup in documentation

#### **4. Makefile Integration**
```makefile
minikube-ingress-setup:
    @echo "Setting up ingress for minikube..."
    minikube addons enable ingress
    @echo "Add this to /etc/hosts: $$(minikube ip) project-template.local"
```

#### **Development**
```bash
# Access application with clean URL
curl http://project-template.local/health
# Instead of: kubectl port-forward svc/project-template 8080:8080
```

#### **Production**
```yaml
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-tls-secret
      hosts:
        - api.example.com
```

#### **Must Have**
- [ ] Conditional ingress resource creation
- [ ] Support for NGINX ingress controller
- [ ] Kubernetes API version compatibility (1.14-1.29+)
- [ ] Basic HTTP routing with path-based rules
- [ ] Integration with existing Helm chart structure

#### **Should Have**
- [ ] TLS/SSL certificate support
- [ ] Multiple host configuration
- [ ] Custom annotation support for different ingress controllers
- [ ] Minikube development environment integration
- [ ] Documentation with setup examples

#### **Could Have**
- [ ] Support for Traefik, HAProxy, and other ingress controllers
- [ ] Advanced routing rules (header-based, weight-based)
- [ ] Rate limiting and security annotations
- [ ] Ingress class auto-detection

#### **File Structure**
```
helm/
├── templates/
│   ├── ingress.yaml          # New ingress template
│   └── ...existing files
├── configs/
│   └── minikube/
│       └── values.test.yaml  # Updated with ingress config
└── values.yaml               # Updated with ingress section
```

#### **Configuration Examples**

**Basic Local Development:**
```yaml
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: project-template.local
      paths:
        - path: /
          pathType: Prefix
```

**Production with TLS:**
```yaml
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.production.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-tls
      hosts:
        - api.production.com
```

#### **Functional Tests**
- [ ] Ingress resource creates successfully when enabled
- [ ] HTTP traffic routes correctly to application service
- [ ] Multiple path configurations work as expected
- [ ] TLS termination functions properly
- [ ] Ingress disabled by default doesn't create resources

#### **Integration Tests**
- [ ] Minikube + NGINX ingress controller setup
- [ ] Helm chart installation with ingress enabled
- [ ] External access verification through configured hostnames
- [ ] SSL/TLS certificate integration testing

#### **Required Documentation**
- [ ] README.md section on ingress configuration
- [ ] Helm chart values.yaml comments explaining ingress options
- [ ] Development setup guide with minikube ingress
- [ ] Production deployment examples with various ingress controllers
- [ ] Troubleshooting guide for common ingress issues

#### **Examples Needed**
- [ ] Basic HTTP ingress setup
- [ ] HTTPS with Let's Encrypt certificates
- [ ] Multiple environment configurations
- [ ] Custom domain setup instructions

### **Breaking Changes**
None expected. This is a purely additive feature with ingress disabled by default.

### **Dependencies**
- Kubernetes cluster with ingress controller installed
- Helm 3.x
- For development: Minikube with ingress addon

### **Priority**
**Medium** - Improves development experience and enables production deployment patterns

### **Additional Context**
This feature aligns with modern Kubernetes deployment practices and would significantly improve both development workflow and production deployment capabilities. The implementation should be backward-compatible and follow established Helm chart patterns.

### **Acceptance Criteria**
- [ ] Ingress template renders correctly with various configurations
- [ ] Default values maintain backward compatibility (ingress disabled)
- [ ] Minikube development environment works with ingress enabled
- [ ] Documentation includes setup and troubleshooting guides
- [ ] Makefile includes ingress setup helpers
- [ ] All configuration options are properly validated and documented
