### ISSUE TITLE
[FEATURE] Skaffold support

### ISSUE THREAD

**Issue by sorvihead** [sorvihead/vscode-python-template#2]
### **Purpose**
Add Skaffold configuration template to enable automated Kubernetes development workflow for local development and production deployment.

### **Current Gap**
Template lacks modern Kubernetes development workflow - developers must manually run:
```bash
make docker-build && make helm-deploy
```

#### **skaffold.yaml**
```yaml
apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: project-template
      sync:
        manual:
          - src: "src/**/*.py"
            dest: /app/src
manifests:
  helm:
    releases:
      - name: project-template
        chartPath: helm
        valuesFiles:
          - helm/configs/minikube/values.test.yaml
portForward:
  - resourceType: service
    resourceName: project-template
    port: 8080
profiles:
  - name: debug
    manifests:
      helm:
        releases:
          - name: project-template
            setValues:
              env.DEBUG: "true"
```

#### **Makefile additions**
```makefile
skaffold-dev: minikube-setup
    skaffold dev --cleanup=false

skaffold-debug: minikube-setup  
    skaffold dev --profile=debug
```

### **Template Benefits**
- **Local Development**: Hot-reload on code changes
- **Production Ready**: Same config works for CI/CD
- **Complete Example**: Shows Helm + Skaffold integration

### **Acceptance Criteria**
- [ ] Working skaffold.yaml template
- [ ] Makefile integration
- [ ] Documentation in README
- [ ] File sync for Python hot-reload
- [ ] Debug profile example

### **Priority**
Medium - Improves template completeness for modern Kubernetes workflows
