### ISSUE TITLE
[FEATURE] Github workflows support

### ISSUE THREAD

**Issue by sorvihead** [sorvihead/vscode-python-template#3]
### **Purpose**
Add GitHub Actions workflow templates for automated testing, building, and deployment to provide complete CI/CD examples for both local development and production deployment scenarios.

### **Current Gap**
Template project lacks CI/CD workflow examples, requiring users to:
- Manually set up testing pipelines
- Configure container builds and registry pushes
- Handle deployment automation
- Set up security scanning and quality checks

#### **.github/workflows/ci.yml** - Basic CI Pipeline
```yaml
name: CI Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        run: make test
      - name: Run linting
        run: make lint
```

#### **.github/workflows/build.yml** - Container Build
```yaml
name: Build and Push
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker image
        run: |
          docker build -t ${{ github.repository }}:${{ github.ref_name }} .
          # Add registry push logic here
```

#### **.github/workflows/deploy.yml** - Deployment Pipeline
```yaml
name: Deploy
on:
  workflow_run:
    workflows: ["Build and Push"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging
        run: |
          # Add Helm deployment logic
          helm upgrade --install app ./helm
```

#### **Basic Workflows**
- **CI Pipeline**: Testing, linting, type checking
- **Build Pipeline**: Container image building and pushing
- **Deploy Pipeline**: Helm-based deployment automation
- **Security Scanning**: Container and dependency vulnerability checks

#### **Integration Examples**
- **Makefile integration**: Reuse existing make targets
- **Helm deployment**: Automated chart deployment
- **Multi-environment**: Staging and production pipelines
- **Conditional execution**: Branch-based workflow triggers

### **Makefile Integration**
```makefile
# Add workflow validation
workflow-validate:
    act --list
    act --dry-run

workflow-test:
    act -j test
```

### **Acceptance Criteria**
- [ ] Working CI workflow for testing and linting
- [ ] Container build workflow with tagging strategy
- [ ] Deployment workflow using existing Helm charts
- [ ] Security scanning workflow template
- [ ] Documentation in README with workflow explanations
- [ ] Integration with existing Makefile targets

### **Priority**
Medium - Completes template with production-ready CI/CD patterns

### **Additional Context**
This addresses the template's goal of providing complete examples for both local development and production deployment by including automated pipeline templates that teams can customize for their needs.
